Repository Samsung/tizen-docs, pull requests merged in 2019-11, with the labels that each got.

#884 [ACR-1423] Add sticker feature
  docs/application/native/guides/app-management/media/sticker.png
  docs/application/native/guides/app-management/overview.md
  docs/application/native/guides/app-management/sticker.md
  docs/application/toc_all.md
Labels: Scheduled

#850 Add introductions of Anchor SoM Module
  docs/iot/iot-partners/anchor/anchor.md
  docs/iot/iot-partners/anchor/media/anchor3basePICo.png
  docs/iot/iot-partners/anchor/media/anchor3somDiagramO.png
  docs/iot/iot-partners/anchor/media/anchor3somPICo.png
  docs/iot/iot-partners/anchor/media/anchor5basePIC1.png
  docs/iot/iot-partners/anchor/media/anchor5somDiagram.png
  docs/iot/iot-partners/anchor/media/anchor5somPIC.png
  docs/iot/iot-partners/media/anchor3basePICo.png
  docs/iot/iot-partners/media/anchor3somDiagramO.png
  docs/iot/iot-partners/media/anchor3somPICo.png
  docs/iot/iot-partners/media/anchor5basePIC1.png
  docs/iot/iot-partners/media/anchor5somDiagram.png
  docs/iot/iot-partners/media/anchor5somPIC.png
  docs/iot/toc_all.md
Labels: Scheduled

#843 Change the order of menu tree in terms of priority.
  docs/application/get-started/mobile.md
  docs/application/get-started/tv.md
  docs/application/get-started/wearable.md
  docs/application/index.md
  docs/application/toc_all.md
Labels: Scheduled

#921 Add platform details to release notes
  docs/platform/release-notes/tizen-1-0.md
  docs/platform/release-notes/tizen-2-0.md
  docs/platform/release-notes/tizen-2-1.md
  docs/platform/release-notes/tizen-2-2-1.md
  docs/platform/release-notes/tizen-2-2.md
  docs/platform/release-notes/tizen-2-3-1.md
  docs/platform/release-notes/tizen-2-3-2.md
  docs/platform/release-notes/tizen-2-3.md
  docs/platform/release-notes/tizen-2-4.md
  docs/platform/release-notes/tizen-3-0-m2.md
  docs/platform/release-notes/tizen-3-0-m3.md
  docs/platform/release-notes/tizen-3-0-m4.md
  docs/platform/release-notes/tizen-3-0-milestones.md
  docs/platform/release-notes/tizen-4-0-m1.md
  docs/platform/release-notes/tizen-4-0-m2.md
  docs/platform/release-notes/tizen-4-0-m3.md
  docs/platform/release-notes/tizen-5-0-m1.md
  docs/platform/release-notes/tizen-5-0-m2.md
  docs/platform/release-notes/tizen-5-5-m1.md
  docs/platform/release-notes/tizen-5-5-m2.md
Labels: Scheduled

#905 Update privilege document according to the latest privilege info
  docs/application/dotnet/tutorials/sec-privileges.md
  docs/application/native/tutorials/details/sec-privileges.md
Labels: Scheduled

#935 Fix broken links
  docs/application/dotnet/guides/connectivity/bluetooth.md
  docs/application/dotnet/guides/device/attached-devices.md
  docs/application/dotnet/guides/location-sensors/maps.md
  docs/application/dotnet/guides/messaging/push.md
  docs/application/dotnet/guides/nui/animation.md
  docs/application/dotnet/guides/nui/customview.md
  docs/application/dotnet/guides/nui/setup-ubuntu.md
  docs/application/dotnet/guides/nui/styling-controls-with-JSON.md
  docs/application/dotnet/guides/nui/visuals.md
  docs/application/get-started/mobile.md
  docs/application/get-started/tv.md
  docs/application/get-started/wearable.md
  docs/application/native/api/mobile/latest
  docs/application/native/api/wearable/latest
  docs/application/native/guides/app-management/app-icons.md
  docs/application/native/guides/connectivity/bluetooth.md
  docs/application/native/guides/connectivity/http-api.md
  docs/application/native/guides/connectivity/internet-download.md
  docs/application/native/guides/index.md
  docs/application/native/guides/multimedia/openal.md
  docs/application/native/guides/personal/data-sync.md
  docs/application/native/guides/personal/oauth.md
  docs/application/native/guides/ui/efl/data-types.md
  docs/application/native/guides/ui/efl/mobile/component-calendar.md
  docs/application/native/guides/ui/efl/wearable/component-circle-option.md
  docs/application/native/tutorials/process/debugging-app.md
  docs/application/toc_all.md
  docs/application/web/get-started/wearable-widget/first-app-widget.md
  docs/application/web/guides/error/error.md
  docs/application/web/guides/w3c/multimedia/video-audio.md
  docs/application/web/guides/w3c/security/iframe.md
  docs/application/web/guides/w3c/storage/indexdb.md
  docs/application/web/guides/w3c/supplement/typedarray.md
  docs/get-started.md
  docs/glossary.md
  docs/iot/get-started/rpi3-5.0.md
  docs/iot/get-started/things-app-development-5.0.md
  docs/iot/guides/iot-api.md
  docs/iot/guides/things-api-device-5.0.md
  docs/iot/iot-partners/anchor/anchor.md
  docs/platform/developing/contributing.md
  docs/platform/porting/system.md
  docs/platform/reference/mic/mic-faq.md
  docs/platform/what-is-tizen/profiles/mobile.md
Labels: Review/Requested

#939 Update DRM PDFs to nonDRM PDFs
  docs/platform/compliance/media/tizen-2.3.1-compliance-specification-for-wearable-profile-v1.0.pdf
  docs/platform/compliance/media/tizen-2.4-compliance-specification-for-mobile-profile-v1.0.pdf
  docs/platform/compliance/media/tizen-2.4-compliance-specification-for-tv-profile-v1.0.pdf
  docs/platform/compliance/media/tizen-3.0-compliance-specification-for-ivi-profile-v1.0_1.pdf
  docs/platform/compliance/media/tizen-3.0-crosswalk-apis-for_ivi-v1.0_0.pdf
  docs/platform/compliance/media/tizen-3.0-wrt-core-spec.pdf
  docs/platform/compliance/media/tizen_branding_request_form_for_tizen_mobile_profile_v1.0_1.pdf
Labels: Review/Scheduled

#816 [NUI] Add NUI Quickstart page
  docs/application/dotnet/get-started/nui/media/nui-hello-world.png
  docs/application/dotnet/get-started/nui/media/tizen_project_wizard_capture_template1_1.png
  docs/application/dotnet/get-started/nui/media/tizen_project_wizard_capture_template1_2.png
  docs/application/dotnet/get-started/nui/media/tizen_project_wizard_capture_template2.png
  docs/application/dotnet/get-started/nui/media/tizen_project_wizard_capture_template3.png
  docs/application/dotnet/get-started/nui/media/tizen_project_wizard_capture_template4.png
  docs/application/dotnet/get-started/nui/media/tizen_project_wizard_capture_template5.png
  docs/application/dotnet/get-started/nui/media/tizen_project_wizard_capture_template6.png
  docs/application/dotnet/get-started/nui/quickstart.md
  docs/application/dotnet/get-started/overview.md
  docs/application/dotnet/guides/nui/hello-world.md
  docs/application/dotnet/guides/nui/media/hello-world.png
  docs/application/dotnet/guides/nui/overview.md
  docs/application/dotnet/guides/nui/setup-ubuntu.md
  docs/application/dotnet/guides/nui/textlabel.md
  docs/application/toc_all.md
Labels: Review/Scheduled

#930 Change screenshots of target devices
  docs/application/native/get-started/mobile/first-app.md
  docs/application/native/get-started/wearable-watch/first-app-watch.md
  docs/application/native/get-started/wearable-watch/media/app_run_multiple_emulators.png
  docs/application/native/get-started/wearable-watch/media/app_run_multiple_emulators_w.png
  docs/application/native/get-started/wearable-watch/media/emulator_launch_w.png
  docs/application/native/get-started/wearable-watch/media/remote_allow_gear.png
  docs/application/native/get-started/wearable-watch/media/remote_allow_gear_ww.png
  docs/application/native/get-started/wearable-watch/media/remote_connected_w.png
  docs/application/native/get-started/wearable-watch/media/remote_connected_ww.png
  docs/application/native/get-started/wearable-watch/media/testing_your_app_on_gear1.png
  docs/application/native/get-started/wearable-watch/media/testing_your_app_on_gear11.png
  docs/application/native/get-started/wearable-watch/media/testing_your_app_on_gear2.png
  docs/application/native/get-started/wearable-watch/media/testing_your_app_on_gear3.png
  docs/application/native/get-started/wearable-watch/media/testing_your_app_on_gear4.png
  docs/application/native/get-started/wearable-watch/media/testing_your_app_on_gear6.png
  docs/application/native/get-started/wearable-watch/media/testing_your_app_on_gear7.png
  docs/application/native/get-started/wearable-watch/media/wearable_settings_app.png
  docs/application/native/get-started/wearable-widget/first-app-widget.md
  docs/application/native/get-started/wearable-widget/media/app_run_multiple_emulators.png
  docs/application/native/get-started/wearable-widget/media/remote_allow_gear.png
  docs/application/native/get-started/wearable-widget/media/remote_allow_gear_ww.png
  docs/application/native/get-started/wearable-widget/media/remote_connected_w.png
  docs/application/native/get-started/wearable-widget/media/remote_connected_ww.png
  docs/application/native/get-started/wearable-widget/media/testing_your_app_on_gear1.png
  docs/application/native/get-started/wearable-widget/media/testing_your_app_on_gear2.png
  docs/application/native/get-started/wearable-widget/media/testing_your_app_on_gear3.png
  docs/application/native/get-started/wearable-widget/media/testing_your_app_on_gear4.png
  docs/application/native/get-started/wearable-widget/media/testing_your_app_on_gear6.png
  docs/application/native/get-started/wearable-widget/media/testing_your_app_on_gear7.png
  docs/application/native/get-started/wearable-widget/media/wearable_settings_app.png
  docs/application/native/get-started/wearable/first-app.md
  docs/application/native/get-started/wearable/media/app_run_multiple_emulators.png
  docs/application/native/get-started/wearable/media/app_run_multiple_emulators_w.png
  docs/application/native/get-started/wearable/media/remote_allow_gear.png
  docs/application/native/get-started/wearable/media/remote_allow_gear_ww.png
  docs/application/native/get-started/wearable/media/remote_conn_add_ww.png
  docs/application/native/get-started/wearable/media/remote_conn_device.png
  docs/application/native/get-started/wearable/media/remote_conn_mgr.png
  docs/application/native/get-started/wearable/media/remote_conn_mgr_ww.png
  docs/application/native/get-started/wearable/media/remote_conn_new_ww.png
  docs/application/native/get-started/wearable/media/remote_conn_scan.png
  docs/application/native/get-started/wearable/media/remote_conn_scan_icon.png
  docs/application/native/get-started/wearable/media/remote_connect_ww.png
  docs/application/native/get-started/wearable/media/remote_connected_w.png
  docs/application/native/get-started/wearable/media/remote_connected_ww.png
  docs/application/native/get-started/wearable/media/testing_your_app_on_gear1.png
  docs/application/native/get-started/wearable/media/testing_your_app_on_gear2.png
  docs/application/native/get-started/wearable/media/testing_your_app_on_gear3.png
  docs/application/native/get-started/wearable/media/testing_your_app_on_gear4.png
  docs/application/native/get-started/wearable/media/testing_your_app_on_gear6.png
  docs/application/native/get-started/wearable/media/testing_your_app_on_gear7.png
  docs/application/native/get-started/wearable/media/wearable_settings_app.png
Labels: Review/Scheduled

#925 Add style for squared-button
  docs/application/dotnet/api/overview.md
  docs/application/dotnet/api/xamarin-forms-limitations.md
Labels: Review/Scheduled

#936 Change screenshots of target devices for Wearable Web
  docs/application/web/get-started/wearable-watch/first-app-watch.md
  docs/application/web/get-started/wearable-watch/media/app_run_multiple_emulators.png
  docs/application/web/get-started/wearable-watch/media/remote_allow_gear.png
  docs/application/web/get-started/wearable-watch/media/remote_allow_gear_ww.png
  docs/application/web/get-started/wearable-watch/media/remote_connected_w.png
  docs/application/web/get-started/wearable-watch/media/remote_connected_ww.png
  docs/application/web/get-started/wearable-watch/media/testing_your_app_on_gear1.png
  docs/application/web/get-started/wearable-watch/media/testing_your_app_on_gear11.png
  docs/application/web/get-started/wearable-watch/media/testing_your_app_on_gear2.png
  docs/application/web/get-started/wearable-watch/media/testing_your_app_on_gear3.png
  docs/application/web/get-started/wearable-watch/media/testing_your_app_on_gear4.png
  docs/application/web/get-started/wearable-watch/media/testing_your_app_on_gear6.png
  docs/application/web/get-started/wearable-watch/media/testing_your_app_on_gear7.png
  docs/application/web/get-started/wearable-watch/media/wearable_settings_app.png
  docs/application/web/get-started/wearable-widget/first-app-widget.md
  docs/application/web/get-started/wearable-widget/media/app_run_multiple_emulators.png
  docs/application/web/get-started/wearable-widget/media/emulator_window_wearable.png
  docs/application/web/get-started/wearable-widget/media/remote_allow_gear.png
  docs/application/web/get-started/wearable-widget/media/remote_allow_gear_ww.png
  docs/application/web/get-started/wearable-widget/media/remote_connected_w.png
  docs/application/web/get-started/wearable-widget/media/remote_connected_ww.png
  docs/application/web/get-started/wearable-widget/media/simple_ui_label_wn_widget.png
  docs/application/web/get-started/wearable-widget/media/testing_your_app_on_gear1.png
  docs/application/web/get-started/wearable-widget/media/testing_your_app_on_gear2.png
  docs/application/web/get-started/wearable-widget/media/testing_your_app_on_gear3.png
  docs/application/web/get-started/wearable-widget/media/testing_your_app_on_gear4.png
  docs/application/web/get-started/wearable-widget/media/testing_your_app_on_gear6.png
  docs/application/web/get-started/wearable-widget/media/testing_your_app_on_gear7.png
  docs/application/web/get-started/wearable-widget/media/wearable_settings_app.png
  docs/application/web/get-started/wearable/first-app.md
  docs/application/web/get-started/wearable/media/app_run_multiple_emulators.png
  docs/application/web/get-started/wearable/media/emulator_window_wearable.png
  docs/application/web/get-started/wearable/media/remote_allow_gear.png
  docs/application/web/get-started/wearable/media/remote_allow_gear_ww.png
  docs/application/web/get-started/wearable/media/remote_conn_add_ww.png
  docs/application/web/get-started/wearable/media/remote_conn_device.png
  docs/application/web/get-started/wearable/media/remote_conn_mgr.png
  docs/application/web/get-started/wearable/media/remote_conn_new_ww.png
  docs/application/web/get-started/wearable/media/remote_conn_scan.png
  docs/application/web/get-started/wearable/media/remote_conn_scan_icon.png
  docs/application/web/get-started/wearable/media/remote_connect_ww.png
  docs/application/web/get-started/wearable/media/remote_connected_w.png
  docs/application/web/get-started/wearable/media/remote_connected_ww.png
  docs/application/web/get-started/wearable/media/testing_your_app_on_gear1.png
  docs/application/web/get-started/wearable/media/testing_your_app_on_gear2.png
  docs/application/web/get-started/wearable/media/testing_your_app_on_gear3.png
  docs/application/web/get-started/wearable/media/testing_your_app_on_gear4.png
  docs/application/web/get-started/wearable/media/testing_your_app_on_gear6.png
  docs/application/web/get-started/wearable/media/testing_your_app_on_gear7.png
  docs/application/web/get-started/wearable/media/wearable_settings_app.png
Labels: Review/Scheduled
