Repository Samsung/tizen-docs, pull requests merged in 2019-08, with the labels that each got.

#796 Synchronize two branches: master and live
  docs/application/dotnet/guides/multimedia/media-controller.md
  docs/application/native/guides/data/data-storages.md
  docs/application/tizen-studio/web-tools/config-editor.md
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Button.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Checkbox.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_ColoredListview.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_DropdownMenu.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Expandable.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_FloatingActions.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_GridView.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_IndexScrollBar.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Navigation.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_PageIndicator.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_PanelChanger.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Popup.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Progress.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Radio.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_SearchInput.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_SectionChanger.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Slider.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Tabs.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_TextEnveloper.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_TextInput.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_ToggleSwitch.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_button.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_checkbox.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_circleprogressbar.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_circularindexscrollbar.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_datepicker.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_list.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_marquee.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_numberpicker.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_pageindicator.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_popup.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_processing.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_sectionchanger.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_selector.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_slider.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_snaplistview.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_timepicker.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_toggleswitch.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_virtuallist.htm
Labels: publish

#788 Removed ATI and Intel Graphics card information
  docs/application/tizen-studio/setup/prerequisites.md
Labels: Tizen Studio

#792 Remove Dynamic Analyzer from Tizen Studio > Web Tools.
  docs/application/tizen-studio/web-tools/debugging.md
  docs/application/toc_all.md
Labels: Tizen Studio

#801 Add ToC to wearable popup documentation
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_popup.htm
Labels: TAU

#797 Restore TAU documentation changes - links
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Button.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Checkbox.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_ColoredListview.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_DropdownMenu.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Expandable.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_FloatingActions.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_GridView.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_IndexScrollBar.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Navigation.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_PageIndicator.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_PanelChanger.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Popup.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Progress.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Radio.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_SearchInput.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_SectionChanger.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Slider.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Tabs.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_TextEnveloper.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_TextInput.htm
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_ToggleSwitch.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_button.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_checkbox.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_circleprogressbar.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_circularindexscrollbar.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_datepicker.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_list.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_marquee.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_numberpicker.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_pageindicator.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_popup.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_processing.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_sectionchanger.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_selector.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_slider.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_snaplistview.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_timepicker.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_toggleswitch.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_virtuallist.htm
Labels: TAU
