Repository Samsung/tizen-docs, pull requests merged in 2019-12, with the labels that each got.

#972 Synchronize two branches: master and live
  docs/application/dotnet/get-started/overview.md
  docs/application/native/get-started/overview.md
  docs/application/tizen-studio/common-tools/log-view.md
  docs/application/tizen-studio/release-notes/3-6-release-notes.md
  docs/application/tizen-studio/release-notes/release-notes.md
  docs/application/toc_all.md
  docs/application/vstools-mac/overview.md
  docs/application/vstools/index.md
  docs/application/web/get-started/overview.md
  docs/application/web/guides/w3c/perf-opt/performance-improvement.md
Labels: publish

#903 [ACR-1431] Add Image Classification guide
  docs/application/native/guides/multimedia/image-classification.md
  docs/application/native/guides/multimedia/media-vision.md
  docs/application/toc_all.md
Labels: Review/Scheduled

#959 Add Wearable slider example for Tizen 5.5 TAU documentation
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_circularindexscrollbar.htm
  docs/application/web/api/5.5/ui_fw_api/Base/popup.htm
  docs/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_Button.htm
  docs/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_Checkbox.htm
  docs/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_ColoredListview.htm
  docs/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_Coverflow.htm
  docs/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_Dimmer.htm
  docs/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_DropdownMenu.htm
  docs/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_Expandable.htm
  docs/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_FloatingActions.htm
  docs/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_Graph.htm
  docs/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_GridView.htm
  docs/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_IndexScrollBar.htm
  docs/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_Interactive3D.htm
  docs/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_Navigation.htm
  docs/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_PageIndicator.htm
  docs/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_PanelChanger.htm
  docs/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_Popup.htm
  docs/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_Progress.htm
  docs/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_Radio.htm
  docs/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_SearchInput.htm
  docs/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_SectionChanger.htm
  docs/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_Slider.htm
  docs/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_Tabs.htm
  docs/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_TextEnveloper.htm
  docs/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_TextInput.htm
  docs/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_ToggleSwitch.htm
  docs/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_Coverflow.htm
  docs/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_button.htm
  docs/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_checkbox.htm
  docs/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_circleprogressbar.htm
  docs/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_circularindexscrollbar.htm
  docs/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_datepicker.htm
  docs/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_dimmer.htm
  docs/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_graph.htm
  docs/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_interactive3D.htm
  docs/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_list.htm
  docs/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_marquee.htm
  docs/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_numberpicker.htm
  docs/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_pageindicator.htm
  docs/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_popup.htm
  docs/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_processing.htm
  docs/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_sectionchanger.htm
  docs/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_selector.htm
  docs/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_slider.htm
  docs/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_snaplistview.htm
  docs/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_timepicker.htm
  docs/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_toggleswitch.htm
  docs/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_viewSwitcher.htm
  docs/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_virtuallist.htm
Labels: TAU, testing

#981 Append proper screen to checkbox and radio element
  docs/application/web/api/5.0/images/checkbox-wearable.png
  docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Checkbox.htm
  docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_checkbox.htm
  docs/application/web/api/5.5/images/checkbox-wearable.png
  docs/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_checkbox.htm
Labels: TAU
