Repository Samsung/tizen-docs, pull requests merged in 2020-03, with the labels that each got.

#1036 Style Update: VS Code Ext
  docs/application/vscode-ext/dotnet.md
  docs/application/vscode-ext/index.md
  docs/application/vscode-ext/web.md
Labels: testing

#1041 Change screenshots for deploying packages
  docs/application/dotnet/get-started/mobile/first-app.md
  docs/application/dotnet/get-started/mobile/media/vs_emulator_dropdown.png
  docs/application/dotnet/get-started/mobile/media/vs_emulator_launch_mobile.png
  docs/application/dotnet/get-started/tv/first-app.md
  docs/application/dotnet/get-started/tv/media/vs_emulator_dropdown.png
  docs/application/dotnet/get-started/tv/media/vs_emulator_launch_tv.png
  docs/application/dotnet/get-started/wearable/first-app.md
  docs/application/dotnet/get-started/wearable/media/vs_emulator_dropdown.png
  docs/application/dotnet/get-started/wearable/media/vs_emulator_launch.png
  docs/application/dotnet/get-started/wearable/media/vs_emulator_launch_wearable.png
Labels: Review/Requested

#1044 Synchronize two branches: master and live
  docs/application/dotnet/get-started/mobile/first-app.md
  docs/application/dotnet/get-started/mobile/media/vs_emulator_dropdown.png
  docs/application/dotnet/get-started/mobile/media/vs_emulator_launch_mobile.png
  docs/application/dotnet/get-started/tv/first-app.md
  docs/application/dotnet/get-started/tv/media/vs_emulator_dropdown.png
  docs/application/dotnet/get-started/tv/media/vs_emulator_launch_tv.png
  docs/application/dotnet/get-started/wearable/first-app.md
  docs/application/dotnet/get-started/wearable/media/vs_emulator_dropdown.png
  docs/application/dotnet/get-started/wearable/media/vs_emulator_launch.png
  docs/application/dotnet/get-started/wearable/media/vs_emulator_launch_wearable.png
  docs/platform/compliance/compliance-specification.md
  docs/platform/compliance/media/tizen-5.5-compliance-specification-for-tv-profile-v0.95beta.pdf
Labels: publish

#1026 Create a new Get Started guide for .NET XAML Wearable
  docs/application/dotnet/get-started/overview.md
  docs/application/dotnet/get-started/wearable/first-app.md
  docs/application/dotnet/get-started/wearable/first-xaml-app.md
  docs/application/dotnet/get-started/wearable/media/cs_first_building_emulator_xaml.png
  docs/application/dotnet/get-started/wearable/media/cs_first_creating_configure_project_xaml.png
  docs/application/dotnet/get-started/wearable/media/cs_first_creating_new_project_xaml.png
  docs/application/dotnet/get-started/wearable/media/cs_first_packaging_content_xaml.png
  docs/application/dotnet/get-started/wearable/media/vs_emulator_launch_xaml.png
  docs/application/dotnet/get-started/wearable/media/vs_solution_explorer_xaml.png
  docs/application/dotnet/get-started/wearable/media/wearable_xamal_app_enhanced1.png
  docs/application/dotnet/get-started/wearable/media/wearable_xamal_app_enhanced2.png
  docs/application/get-started/wearable.md
  docs/application/toc_all.md
Labels: Review/Requested
